### ISSUE TITLE
Recommended quick/easy deployment?

### ISSUE THREAD

**Issue by jamespacileo** [sneezeparty/soupy#1]
Hi, what platform do you recommend deploy this on
and if you're looking for some help to add a few features would you be interested.

I'd love to get some friends/family to try this out, think it's an easy way to get people interested and involved in the recent AI developments. It'll make them feel a bit more included :)

**Comment by jamespacileo** [comment]
my Discord username is .paxilius

**Comment by sneezeparty** [comment]
> Hi, what platform do you recommend deploy this on and if you're looking for some help to add a few features would you be interested.
> 
> I'd love to get some friends/family to try this out, think it's an easy way to get people interested and involved in the recent AI developments. It'll make them feel a bit more included :)

Do you have a machine you're currently running Python on?
